import { CalendarDays, MessageCircle, Video, X } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import Button from '../components/Button'
import Card from '../components/Card'
import PageHeader from '../components/PageHeader'
import { addWalletTransaction, getAppointments, updateAppointment, type Appointment } from '../services/localStorage'

const formatDate = (date: string) => new Intl.DateTimeFormat('en-IN', { dateStyle: 'full', timeZone: 'UTC' }).format(new Date(`${date}T00:00:00Z`))
export default function Appointments() {
  const [appointments, setAppointments] = useState(() => getAppointments())
  const [cancelId, setCancelId] = useState<string | null>(null)
  function cancel(appointment: Appointment) { setAppointments(updateAppointment(appointment.id, { status: 'cancelled' })); addWalletTransaction({ amount: 0, coins: appointment.coins, type: 'refund', description: `Refund for cancelled ${appointment.doctorName} consultation` }); setCancelId(null) }
  const upcoming = appointments.filter((item) => item.status === 'upcoming')
  const past = appointments.filter((item) => item.status !== 'upcoming')
  return <><PageHeader eyebrow="Your care plan" title="My appointments" description="Manage your simulated consultations and open a private-looking demo room." icon={CalendarDays} /><div className="appointment-section"><div className="section-heading"><h2>Upcoming</h2><Link className="card-link" to="/doctors">Find another doctor</Link></div>{upcoming.length === 0 ? <Card className="empty-state"><CalendarDays size={28} /><h2>No upcoming appointments</h2><p>Book a fictional demo consultation to see it here.</p></Card> : <div className="appointment-list">{upcoming.map((item) => <AppointmentCard key={item.id} appointment={item} onCancel={() => setCancelId(item.id)} />)}</div>}</div><div className="appointment-section"><div className="section-heading"><h2>Past and cancelled</h2></div>{past.length === 0 ? <Card><p>Your completed or cancelled appointments will appear here.</p></Card> : <div className="appointment-list">{past.map((item) => <AppointmentCard key={item.id} appointment={item} />)}</div>}</div>{cancelId && <div className="modal-backdrop"><div className="modal-card compact-modal" role="dialog"><button className="modal-close" type="button" onClick={() => setCancelId(null)} aria-label="Close"><X size={18} /></button><h2>Cancel appointment?</h2><p>This demo policy returns the consultation coins immediately. No real appointment or payment is affected.</p><div className="form-actions"><Button variant="secondary" type="button" onClick={() => setCancelId(null)}>Keep appointment</Button><Button type="button" onClick={() => { const item = appointments.find((appointment) => appointment.id === cancelId); if (item) cancel(item) }}>Cancel and refund</Button></div></div></div>}</>
}
function AppointmentCard({ appointment, onCancel }: { appointment: Appointment; onCancel?: () => void }) { return <Card className="appointment-card"><div className="appointment-doctor-avatar">{appointment.doctorName.split(' ').slice(-1)[0][0]}</div><div className="appointment-info"><div className="card-top"><div><h2>{appointment.doctorName}</h2><p>{formatDate(appointment.date)} · {appointment.time}</p></div><span className={`status-pill ${appointment.status}`}>{appointment.status}</span></div><div className="doctor-meta"><span>{appointment.consultationType === 'chat' ? <MessageCircle size={15} /> : <Video size={15} />}{appointment.consultationType} · {appointment.duration} min</span><span>◈ {appointment.coins} coins</span></div><div className="form-actions">{appointment.status === 'upcoming' && <Link className="button button-primary" to={`/consultation/${appointment.id}`}>Open consultation</Link>}{appointment.status === 'upcoming' && onCancel && <Button variant="secondary" type="button" onClick={onCancel}>Cancel</Button>}</div></div></Card> }
