import { Activity, BarChart3, CalendarDays, HeartPulse, LockKeyhole, Sparkles } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import Card from '../components/Card'
import PageHeader from '../components/PageHeader'
import { getCycleRecords, getRecordsForPeriod, getWellnessHistory, type CycleRecord, type WellnessPeriod, type WellnessRecord } from '../services/localStorage'

const periodLabels: Record<WellnessPeriod, string> = { week: 'This Week', month: 'This Month', '3months': 'Last 3 Months', '6months': 'Last 6 Months' }
const fullDateFormatter = new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeZone: 'UTC' })

type Metric = 'energy' | 'sleep'
type Phase = 'Menstrual' | 'Follicular' | 'Ovulation' | 'Luteal'

function formatDate(date: string): string { return fullDateFormatter.format(new Date(`${date}T00:00:00Z`)) }
function average(values: number[]): string { return values.length ? (values.reduce((sum, value) => sum + value, 0) / values.length).toFixed(1) : 'Not enough data' }
function mostCommon(values: string[]): string { if (!values.length) return 'Not enough data'; const counts = new Map<string, number>(); values.forEach((value) => counts.set(value, (counts.get(value) ?? 0) + 1)); return [...counts.entries()].sort((first, second) => second[1] - first[1])[0][0] }
function dayDifference(first: string, second: string): number { return Math.round((new Date(`${first}T00:00:00Z`).getTime() - new Date(`${second}T00:00:00Z`).getTime()) / 86400000) }
function phaseForDay(day: number, cycle: CycleRecord): Phase { const ovulationDay = Math.max(cycle.periodLength + 1, cycle.cycleLength - 14); if (day <= cycle.periodLength) return 'Menstrual'; if (day < ovulationDay) return 'Follicular'; if (day === ovulationDay) return 'Ovulation'; return 'Luteal' }

function OverviewCards({ cycles, wellness }: { cycles: CycleRecord[]; wellness: WellnessRecord[] }) { const cycleLengths = cycles.map((cycle) => cycle.cycleLength); const periodLengths = cycles.map((cycle) => cycle.periodLength); const cards = [['Cycles Tracked', cycles.length ? String(cycles.length) : 'Not enough data', CalendarDays], ['Average Cycle', cycleLengths.length ? `${average(cycleLengths)} days` : 'Not enough data', Activity], ['Average Period', periodLengths.length ? `${average(periodLengths)} days` : 'Not enough data', HeartPulse], ['Wellness Days', wellness.length ? String(wellness.length) : 'Not enough data', Sparkles]] as const; return <div className="insights-overview-grid">{cards.map(([label, value, Icon]) => <Card className="insight-stat" key={label}><Icon className="card-icon" size={22} /><strong>{value}</strong><span>{label}</span></Card>)}</div> }

function CycleLengthGraph({ cycles }: { cycles: CycleRecord[] }) { const sorted = cycles.slice().sort((first, second) => first.startDate.localeCompare(second.startDate)); const width = 720; const height = 220; const left = 40; const right = 20; const top = 20; const bottom = 38; const values = sorted.map((cycle) => cycle.cycleLength); const min = values.length ? Math.min(...values) - 2 : 0; const max = values.length ? Math.max(...values) + 2 : 1; const points = sorted.map((cycle, index) => ({ cycle, x: sorted.length === 1 ? width / 2 : left + (index / (sorted.length - 1)) * (width - left - right), y: top + (1 - (cycle.cycleLength - min) / (max - min || 1)) * (height - top - bottom) })); return sorted.length > 1 ? <div className="insight-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Cycle length over time"><line className="graph-axis" x1={left} y1={top} x2={left} y2={height - bottom} /><line className="graph-axis" x1={left} y1={height - bottom} x2={width - right} y2={height - bottom} /><polyline className="graph-line pink-line" points={points.map((point) => `${point.x},${point.y}`).join(' ')} fill="none" />{points.map((point) => <g key={point.cycle.id}><circle className="graph-point pink-point" cx={point.x} cy={point.y} r="5"><title>{formatDate(point.cycle.startDate)}: {point.cycle.cycleLength} days</title></circle><text x={point.x} y={height - 14} textAnchor="middle">{point.cycle.startDate.slice(5)}</text></g>)}</svg></div> : <p className="chart-note">Track at least two cycles to see cycle length over time.</p> }

function CycleOverview({ cycles }: { cycles: CycleRecord[] }) { const lengths = cycles.map((cycle) => cycle.cycleLength); const periods = cycles.map((cycle) => cycle.periodLength); return <section className="insight-section"><div className="section-heading"><div><div className="eyebrow">Cycle history</div><h2>Cycle Overview</h2></div></div>{cycles.length ? <div className="insight-grid"><Card><div className="mini-stat-list"><div><span>Number of cycles tracked</span><strong>{cycles.length}</strong></div><div><span>Average cycle length</span><strong>{average(lengths)} days</strong></div><div><span>Shortest cycle</span><strong>{Math.min(...lengths)} days</strong></div><div><span>Longest cycle</span><strong>{Math.max(...lengths)} days</strong></div><div><span>Average period length</span><strong>{average(periods)} days</strong></div></div></Card><Card className="chart-card"><h3>Cycle Length Over Time</h3><p>Recorded cycle lengths only. No predictions are shown.</p><CycleLengthGraph cycles={cycles} /></Card></div> : <Card className="empty-inline"><CalendarDays size={24} /><p>Start tracking your cycle to see cycle insights.</p><Link className="button button-secondary" to="/cycle">Track Cycle</Link></Card>}</section> }

function WellnessGraph({ records, metric }: { records: WellnessRecord[]; metric: Metric }) { const sorted = records.slice().sort((first, second) => first.date.localeCompare(second.date)); const width = 720; const height = 220; const left = 40; const right = 20; const top = 20; const bottom = 38; const max = metric === 'energy' ? 5 : 10; const points = sorted.map((record, index) => ({ record, x: sorted.length === 1 ? width / 2 : left + (index / (sorted.length - 1)) * (width - left - right), y: top + (1 - (Number(record[metric === 'energy' ? 'energy' : 'sleepHours']) / max)) * (height - top - bottom) })); return records.length ? <div className="insight-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${metric === 'energy' ? 'Energy' : 'Sleep'} wellness trend`}><line className="graph-axis" x1={left} y1={top} x2={left} y2={height - bottom} /><line className="graph-axis" x1={left} y1={height - bottom} x2={width - right} y2={height - bottom} /><polyline className="graph-line" points={points.map((point) => `${point.x},${point.y}`).join(' ')} fill="none" />{points.map((point) => <g key={point.record.id}><circle className="graph-point" cx={point.x} cy={point.y} r="5"><title>{formatDate(point.record.date)}: {metric === 'energy' ? `${point.record.energy}/5` : `${point.record.sleepHours} hrs`}</title></circle><text x={point.x} y={height - 14} textAnchor="middle">{point.record.date.slice(5)}</text></g>)}</svg></div> : <p className="chart-note">Keep tracking to see your wellness trends.</p> }

function WellnessOverview({ records, period, onPeriodChange }: { records: WellnessRecord[]; period: WellnessPeriod; onPeriodChange: (period: WellnessPeriod) => void }) { const [metric, setMetric] = useState<Metric>('energy'); const filtered = useMemo(() => getRecordsForPeriod(records, period), [records, period]); const mood = mostCommon(filtered.map((record) => record.mood)); const appetite = mostCommon(filtered.map((record) => record.appetite)); const sleepQuality = mostCommon(filtered.map((record) => record.sleepQuality)); return <section className="insight-section"><div className="section-heading trend-heading"><div><div className="eyebrow">Daily check-ins</div><h2>Wellness Overview</h2></div><label className="period-select">Time period<select value={period} onChange={(event) => onPeriodChange(event.target.value as WellnessPeriod)}>{Object.entries(periodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>{records.length ? <><div className="insight-grid wellness-insight-grid"><Card><div className="mini-stat-list"><div><span>Days tracked</span><strong>{filtered.length || 'Not enough data'}</strong></div><div><span>Average energy</span><strong>{filtered.length ? `${average(filtered.map((record) => record.energy))}/5` : 'Not enough data'}</strong></div><div><span>Average sleep</span><strong>{filtered.length ? `${average(filtered.map((record) => record.sleepHours))} hrs` : 'Not enough data'}</strong></div><div><span>Most common mood</span><strong>{mood}</strong></div><div><span>Most common appetite</span><strong>{appetite}</strong></div><div><span>Common sleep quality</span><strong>{sleepQuality}</strong></div></div></Card><Card className="chart-card"><div className="card-top"><div><h3>Wellness Trends</h3><p>Only recorded days in {periodLabels[period].toLowerCase()} are shown.</p></div><div className="metric-toggle"><button className={metric === 'energy' ? 'active' : ''} type="button" onClick={() => setMetric('energy')}>Energy</button><button className={metric === 'sleep' ? 'active' : ''} type="button" onClick={() => setMetric('sleep')}>Sleep</button></div></div><WellnessGraph records={filtered} metric={metric} /></Card></div></> : <Card className="empty-inline"><HeartPulse size={24} /><p>Start your daily wellness check-ins to see wellness insights.</p><Link className="button button-secondary" to="/wellness">Track Wellness</Link></Card>}</section> }

function FrequencyBars({ title, items }: { title: string; items: [string, number][] }) { const max = Math.max(...items.map((item) => item[1]), 1); return <Card className="frequency-card"><h3>{title}</h3>{items.length ? <div className="frequency-list">{items.map(([label, count]) => <div key={label}><div className="frequency-label"><span>{label}</span><strong>{count}</strong></div><div className="frequency-track"><span style={{ width: `${(count / max) * 100}%` }} /></div></div>)}</div> : <p className="muted-copy">No symptom data recorded yet.</p>}</Card> }

function PatternSections({ cycles, wellness, filtered }: { cycles: CycleRecord[]; wellness: WellnessRecord[]; filtered: WellnessRecord[] }) { const symptoms = new Map<string, number>(); cycles.forEach((cycle) => cycle.symptoms?.forEach((symptom) => symptoms.set(symptom, (symptoms.get(symptom) ?? 0) + 1))); const moods = new Map<string, number>(); wellness.forEach((record) => moods.set(record.mood, (moods.get(record.mood) ?? 0) + 1)); const observations = [filtered.length ? `You tracked wellness on ${filtered.length} ${filtered.length === 1 ? 'day' : 'days'} in the selected period.` : '', filtered.length ? `Your average sleep was ${average(filtered.map((record) => record.sleepHours))} hours.` : '', filtered.length ? `Your average energy was ${average(filtered.map((record) => record.energy))}/5.` : '', cycles.length ? `You have tracked ${cycles.length} cycle${cycles.length === 1 ? '' : 's'} locally.` : ''].filter(Boolean); return <section className="insight-section"><div className="section-heading"><div><div className="eyebrow">What your records show</div><h2>Patterns From Your Tracking</h2></div></div><div className="insight-grid"><Card className="pattern-card">{observations.length ? <ul className="observation-list">{observations.map((observation) => <li key={observation}>{observation}</li>)}</ul> : <p className="muted-copy">Keep tracking to see descriptive patterns from your data.</p>}</Card><FrequencyBars title="Frequently Recorded Symptoms" items={[...symptoms.entries()].sort((first, second) => second[1] - first[1])} /><FrequencyBars title="Mood Distribution" items={[...moods.entries()].sort((first, second) => second[1] - first[1])} /></div></section> }

function CycleWellnessComparison({ cycles, wellness }: { cycles: CycleRecord[]; wellness: WellnessRecord[] }) { const phases = ['Menstrual', 'Follicular', 'Ovulation', 'Luteal'] as const; const grouped = phases.map((phase) => { const matching = wellness.filter((record) => { const cycle = cycles.find((candidate) => dayDifference(record.date, candidate.startDate) >= 0 && dayDifference(record.date, candidate.startDate) < candidate.cycleLength); return cycle ? phaseForDay(dayDifference(record.date, cycle.startDate) + 1, cycle) === phase : false }); return { phase, records: matching } }).filter((item) => item.records.length); return grouped.length >= 2 ? <section className="insight-section"><Card><div className="eyebrow">Optional comparison</div><h2>Wellness Across Your Cycle</h2><p>Recorded averages based on wellness entries aligned to saved cycle dates.</p><div className="phase-comparison">{grouped.map(({ phase, records }) => <div key={phase}><strong>{phase}</strong><span>Average energy: {average(records.map((record) => record.energy))}/5</span><span>Average sleep: {average(records.map((record) => record.sleepHours))} hrs</span></div>)}</div></Card></section> : null }

export default function Insights() { const cycles = useMemo(() => getCycleRecords(), []); const wellness = useMemo(() => getWellnessHistory(), []); const [period, setPeriod] = useState<WellnessPeriod>('month'); const filtered = useMemo(() => getRecordsForPeriod(wellness, period), [wellness, period]); const hasData = cycles.length || wellness.length; return <><PageHeader eyebrow="Patterns over time" title="Your Insights" description="Understand your tracking patterns over time." /><p className="privacy-note insights-privacy"><LockKeyhole size={15} />Your tracking data stays on this device. These insights are calculated locally and are not sent to the HerHealth AI assistant.</p>{hasData ? <><OverviewCards cycles={cycles} wellness={wellness} /><CycleOverview cycles={cycles} /><WellnessOverview records={wellness} period={period} onPeriodChange={setPeriod} /><PatternSections cycles={cycles} wellness={wellness} filtered={filtered} /><CycleWellnessComparison cycles={cycles} wellness={wellness} /></> : <Card className="insights-empty"><BarChart3 size={32} /><h2>Your insights will appear as you track your health.</h2><p>Keep your cycle and wellness records together in one private, local view.</p><div className="form-actions"><Link className="button button-primary" to="/cycle">Track Cycle</Link><Link className="button button-secondary" to="/wellness">Track Wellness</Link></div></Card>}</> }
