import { Download, FileHeart, Trash2, Upload } from 'lucide-react'
import { useState, type ChangeEvent } from 'react'
import Card from '../components/Card'
import PageHeader from '../components/PageHeader'
import Button from '../components/Button'
import { deleteMedicalDocument, getMedicalDocuments, saveMedicalDocument, type MedicalDocument, type MedicalDocumentCategory } from '../services/localStorage'

const samples: MedicalDocument[] = [{ id: 'sample-lab', name: 'Sample wellness panel.pdf', type: 'application/pdf', category: 'laboratory', uploadedAt: '2026-10-01T09:00:00.000Z', sample: true }, { id: 'sample-prescription', name: 'Example care plan.pdf', type: 'application/pdf', category: 'prescription', uploadedAt: '2026-10-02T09:00:00.000Z', sample: true }]
const categoryLabels: Record<MedicalDocumentCategory, string> = { laboratory: 'Laboratory report', prescription: 'Prescription', other: 'Other document' }
export default function MedicalRecords() {
  const [documents, setDocuments] = useState(() => [...samples, ...getMedicalDocuments().filter((item) => !samples.some((sample) => sample.id === item.id))])
  const [category, setCategory] = useState<MedicalDocumentCategory>('laboratory')
  const [notice, setNotice] = useState('')
  function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (file.size > 2_000_000) { setNotice('For this prototype, choose a file smaller than 2 MB. Large files are not stored in the browser.'); return } const document: MedicalDocument = { id: `document-${Date.now()}`, name: file.name, type: file.type || 'application/octet-stream', category, uploadedAt: new Date().toISOString() }; try { setDocuments((current) => [document, ...current]); saveMedicalDocument(document); setNotice('File metadata saved locally. The file itself is not uploaded to a server.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'The document could not be saved.') } event.target.value = '' }
  function remove(document: MedicalDocument) { if (document.sample || !window.confirm(`Delete ${document.name}?`)) return; setDocuments((current) => current.filter((item) => item.id !== document.id)); deleteMedicalDocument(document.id) }
  return <><PageHeader eyebrow="Your documents" title="My medical records" description="Keep local metadata for demo reports and prescriptions. Real medical records need secure authenticated storage." icon={FileHeart} /><Card className="records-upload"><div><h2>Add a document</h2><p>Files are limited to 2 MB and are not sent anywhere. Refresh persistence stores metadata only in this demo.</p></div><div className="upload-actions"><label className="field">Category<select value={category} onChange={(event) => setCategory(event.target.value as MedicalDocumentCategory)}><option value="laboratory">Laboratory report</option><option value="prescription">Prescription</option><option value="other">Other</option></select></label><label className="button button-primary upload-label"><Upload size={16} />Choose file<input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={upload} /></label></div>{notice && <p className="success-message">{notice}</p>}</Card><div className="records-grid">{documents.map((document) => <Card className="record-card" key={document.id}><div className="record-icon"><FileHeart size={20} /></div><div className="record-content"><div className="card-top"><div><h2>{document.name}</h2><p>{categoryLabels[document.category]} · {document.type || 'Unknown file type'}</p></div>{document.sample && <span className="status-pill sample">Sample</span>}</div><small>Added {new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(document.uploadedAt))}</small><div className="form-actions">{document.dataUrl ? <a className="button button-secondary" download={document.name} href={document.dataUrl}><Download size={15} />Download</a> : <span className="field-hint">Metadata only</span>}{!document.sample && <Button variant="ghost" type="button" onClick={() => remove(document)} aria-label={`Delete ${document.name}`}><Trash2 size={16} /></Button>}</div></div></Card>)}</div><p className="privacy-note">Sample documents are fictional examples, not medical results or valid medical advice. Uploaded files are intentionally not converted to base64 or stored in localStorage.</p></>
}
