import { Coins, CreditCard, Receipt, X } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import Button from '../components/Button'
import Card from '../components/Card'
import PageHeader from '../components/PageHeader'
import { addWalletTransaction, getWallet, type WalletData } from '../services/localStorage'

const packages = [{ price: 99, coins: 100, label: 'Starter' }, { price: 299, coins: 350, label: 'Popular' }, { price: 599, coins: 750, label: 'Value Pack' }, { price: 1299, coins: 1500, label: 'Premium' }]
const formatDate = (date: string) => new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(date))

export default function Wallet() {
  const [wallet, setWallet] = useState<WalletData>(() => getWallet())
  const [selected, setSelected] = useState<typeof packages[number] | null>(null)
  function confirmPurchase() { if (!selected) return; setWallet(addWalletTransaction({ amount: selected.price, coins: selected.coins, type: 'purchase', description: `${selected.label} package (simulated)` })); setSelected(null) }
  return <><PageHeader eyebrow="Your demo balance" title="HerCoins wallet" description="Use simulated HerCoins to explore consultations. They have no cash value and are not redeemable." icon={Coins} /><div className="wallet-hero"><Card className="wallet-balance"><Coins size={25} /><span>Available HerCoins</span><strong>{wallet.balance.toLocaleString()}</strong><p>Stored only in this browser</p></Card><Card><h2>How it works</h2><p>Choose a package, confirm the simulated purchase, then spend coins on a demo consultation. Every change is recorded below.</p><Link className="button button-secondary" to="/appointments">View appointments</Link></Card></div><Card className="earnings-card"><div><div className="eyebrow">Doctor-side preview</div><h2>Simulated earnings</h2><p>Illustrative only: 1 HerCoin = ₹1 and a 20% platform commission.</p></div><div className="earnings-grid"><span><strong>◈ 420</strong>Completed demo coins</span><span><strong>₹420</strong>Gross estimate</span><span><strong>₹84</strong>Platform commission</span><span><strong>₹336</strong>Doctor estimate</span></div></Card><div className="section-heading"><div><div className="eyebrow">Simulated checkout</div><h2>Choose a package</h2></div></div><div className="package-grid">{packages.map((item) => <Card className={`package-card ${item.label === 'Popular' ? 'featured' : ''}`} key={item.label}><span className="package-label">{item.label}</span><strong>◈ {item.coins}</strong><span>HerCoins</span><h3>₹{item.price.toLocaleString('en-IN')}</h3><Button type="button" onClick={() => setSelected(item)}>Purchase (simulated)</Button></Card>)}</div><Card className="transactions-card"><div className="card-top"><div><Receipt className="card-icon" size={21} /><h2>Transaction history</h2></div><span className="field-hint">Purchases and consultation activity</span></div>{wallet.transactions.length === 0 ? <p>No transactions yet.</p> : <div className="transaction-list">{wallet.transactions.map((item) => <div className="transaction-row" key={item.id}><span><strong>{item.description}</strong><small>{formatDate(item.date)}</small></span><strong className={item.coins > 0 ? 'transaction-positive' : ''}>{item.coins > 0 ? '+' : ''}{item.coins} ◈</strong></div>)}</div>}</Card>{selected && <div className="modal-backdrop"><div className="modal-card compact-modal" role="dialog" aria-modal="true"><button className="modal-close" type="button" onClick={() => setSelected(null)} aria-label="Close"><X size={18} /></button><CreditCard className="card-icon" /><h2>Confirm simulated purchase</h2><p>You are adding <strong>{selected.coins} HerCoins</strong> for <strong>₹{selected.price.toLocaleString('en-IN')}</strong>. No real payment will be taken.</p><div className="form-actions"><Button variant="secondary" type="button" onClick={() => setSelected(null)}>Cancel</Button><Button type="button" onClick={confirmPurchase}>Confirm purchase</Button></div></div></div>}</>
}
