import { Activity, Brain, Check, CircleHelp, Edit3, HeartPulse, Moon, NotebookPen, Sparkles, Trash2 } from 'lucide-react'
import { type FormEvent, useMemo, useState } from 'react'
import Button from '../components/Button'
import Card from '../components/Card'
import PageHeader from '../components/PageHeader'
import { clearWellnessHistory, deleteWellnessRecord, getRecordsForPeriod, getWellnessHistory, saveWellnessRecord, SLEEP_QUALITIES, WELLNESS_APPETITES, WELLNESS_MOODS, type SleepQuality, type WellnessAppetite, type WellnessMood, type WellnessPeriod, type WellnessRecord } from '../services/localStorage'

const today = new Date().toISOString().slice(0, 10)
const dateFormatter = new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeZone: 'UTC' })
const moodIcons = { Happy: Sparkles, Neutral: CircleHelp, Low: Brain, Anxious: Brain, Irritable: Activity, Tired: Moon, Energetic: Activity }
const periodLabels: Record<WellnessPeriod, string> = { week: 'This Week', month: 'This Month', '3months': 'Last 3 Months', '6months': 'Last 6 Months' }

type FormValues = { mood: WellnessMood | ''; energy: number | ''; sleepHours: number | ''; sleepQuality: SleepQuality | ''; appetite: WellnessAppetite | ''; notes: string }
const blankForm: FormValues = { mood: '', energy: '', sleepHours: '', sleepQuality: '', appetite: '', notes: '' }

function formatDate(date: string): string { return dateFormatter.format(new Date(`${date}T00:00:00Z`)) }
function formFromRecord(record: WellnessRecord | null): FormValues { return record ? { mood: record.mood, energy: record.energy, sleepHours: record.sleepHours, sleepQuality: record.sleepQuality, appetite: record.appetite, notes: record.notes ?? '' } : blankForm }
function mostCommon<T extends string>(values: T[]): T | null { if (!values.length) return null; const counts = new Map<T, number>(); values.forEach((value) => counts.set(value, (counts.get(value) ?? 0) + 1)); return [...counts.entries()].sort((first, second) => second[1] - first[1])[0][0] }
function average(values: number[]): string { return values.length ? (values.reduce((sum, value) => sum + value, 0) / values.length).toFixed(1) : '—' }

function WellnessForm({ existing, onSaved }: { existing: WellnessRecord | null; onSaved: (record: WellnessRecord) => void }) {
  const [values, setValues] = useState<FormValues>(() => formFromRecord(existing))
  const update = (field: keyof FormValues, value: string | number) => setValues((current) => ({ ...current, [field]: value }))
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!values.mood || !values.energy || !values.sleepHours || !values.sleepQuality || !values.appetite) return; onSaved(saveWellnessRecord({ ...(existing ? { id: existing.id } : {}), date: today, mood: values.mood, energy: Number(values.energy), sleepHours: Number(values.sleepHours), sleepQuality: values.sleepQuality, appetite: values.appetite, ...(values.notes.trim() ? { notes: values.notes.trim() } : {}) })) }
  return <Card className="wellness-form"><div className="card-top"><div><div className="eyebrow">Today's wellness</div><h2>How are you feeling today?</h2><p>{formatDate(today)}</p></div><NotebookPen className="card-icon" size={23} /></div><form className="cycle-form" onSubmit={submit}><fieldset><legend>Mood</legend><div className="mood-grid">{WELLNESS_MOODS.map((mood) => { const Icon = moodIcons[mood]; return <button type="button" className={`mood-option ${values.mood === mood ? 'selected' : ''}`} key={mood} onClick={() => update('mood', mood)} aria-pressed={values.mood === mood}><Icon size={18} /><span>{mood}</span></button> })}</div></fieldset><fieldset><legend>Energy level</legend><div className="energy-row">{[1, 2, 3, 4, 5].map((level) => <button type="button" className={`energy-option ${values.energy === level ? 'selected' : ''}`} key={level} onClick={() => update('energy', level)} aria-label={`${level} out of 5 energy`} aria-pressed={values.energy === level}>{level}</button>)}</div></fieldset><div className="form-columns"><label className="field">How much did you sleep?<input required min="0" max="24" step="0.5" type="number" value={values.sleepHours} onChange={(event) => update('sleepHours', event.target.value ? Number(event.target.value) : '')} placeholder="e.g. 7.5" /><span className="field-hint">hours</span></label><label className="field">Sleep quality<select required value={values.sleepQuality} onChange={(event) => update('sleepQuality', event.target.value)}><option value="">Select</option>{SLEEP_QUALITIES.map((quality) => <option key={quality}>{quality}</option>)}</select></label></div><label className="field">Appetite<select required value={values.appetite} onChange={(event) => update('appetite', event.target.value)}><option value="">Select</option>{WELLNESS_APPETITES.map((appetite) => <option key={appetite}>{appetite}</option>)}</select></label><label className="field">Anything you'd like to note?<textarea value={values.notes} onChange={(event) => update('notes', event.target.value)} placeholder="Add a short note about how you're feeling today..." /></label><Button type="submit"><Check size={16} />Save Today's Wellness</Button></form><p className="privacy-note"><CircleHelp size={15} />Your wellness data is stored locally on this device and is not sent to the HerHealth AI assistant.</p></Card>
}

function WellnessHistory({ records, onEdit, onDelete }: { records: WellnessRecord[]; onEdit: (record: WellnessRecord) => void; onDelete: (record: WellnessRecord) => void }) { return <section className="wellness-section"><div className="section-heading"><div><div className="eyebrow">Your check-ins</div><h2>Wellness History</h2></div></div>{records.length ? <div className="history-grid">{records.map((record) => <Card className="history-card" key={record.id}><div className="card-top"><div><h3>{formatDate(record.date)}</h3><span className="mood-pill">{record.mood}</span></div><div className="history-actions"><Button variant="ghost" aria-label={`Edit wellness for ${formatDate(record.date)}`} onClick={() => onEdit(record)}><Edit3 size={16} /></Button><Button variant="ghost" aria-label={`Delete wellness for ${formatDate(record.date)}`} onClick={() => onDelete(record)}><Trash2 size={16} /></Button></div></div><div className="history-facts"><span><Activity size={14} />Energy {record.energy}/5</span><span><Moon size={14} />{record.sleepHours} hrs · {record.sleepQuality}</span><span><HeartPulse size={14} />Appetite: {record.appetite}</span></div>{record.notes && <p className="history-note">{record.notes}</p>}</Card>)}</div> : <Card className="empty-state"><HeartPulse size={28} /><h2>No wellness records yet.</h2><p>Complete your first daily check-in to start building a private history.</p></Card>}</section> }

function TrendGraph({ records, metric }: { records: WellnessRecord[]; metric: 'energy' | 'sleep' }) { const width = 760; const height = 230; const padding = { top: 24, right: 25, bottom: 35, left: 42 }; const max = metric === 'energy' ? 5 : 10; const points = records.slice().sort((first, second) => first.date.localeCompare(second.date)).map((record, index, list) => ({ record, x: padding.left + (list.length === 1 ? (width - padding.left - padding.right) / 2 : (index / (list.length - 1)) * (width - padding.left - padding.right)), y: padding.top + (1 - (Number(record[metric === 'energy' ? 'energy' : 'sleepHours']) / max)) * (height - padding.top - padding.bottom) })); const line = points.map((point) => `${point.x},${point.y}`).join(' '); return <div className="trend-graph"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${metric === 'energy' ? 'Energy' : 'Sleep'} trend graph`}><line x1={padding.left} y1={padding.top} x2={padding.left} y2={height - padding.bottom} className="graph-axis" /><line x1={padding.left} y1={height - padding.bottom} x2={width - padding.right} y2={height - padding.bottom} className="graph-axis" />{[0, 1, 2, 3, 4, 5].map((tick) => { const y = padding.top + (1 - tick / max) * (height - padding.top - padding.bottom); return <g key={tick}><line x1={padding.left} y1={y} x2={width - padding.right} y2={y} className="graph-gridline" /><text x={padding.left - 9} y={y + 4} textAnchor="end">{metric === 'energy' ? tick : tick * 2}</text></g> })}{points.length > 1 && <polyline points={line} className="graph-line" fill="none" />}{points.map((point) => <g key={point.record.id}><circle cx={point.x} cy={point.y} r="5" className="graph-point"><title>{formatDate(point.record.date)}: {metric === 'energy' ? `${point.record.energy}/5` : `${point.record.sleepHours} hours`}</title></circle><text x={point.x} y={height - 13} textAnchor="middle">{point.record.date.slice(5)}</text></g>)}</svg>{!records.length && <div className="graph-empty">Not enough data yet. Keep tracking to see your trends.</div>}</div> }

function Trends({ records }: { records: WellnessRecord[] }) { const [period, setPeriod] = useState<WellnessPeriod>('week'); const [metric, setMetric] = useState<'energy' | 'sleep'>('energy'); const filtered = useMemo(() => getRecordsForPeriod(records, period), [records, period]); const moods = filtered.map((record) => record.mood); const appetites = filtered.map((record) => record.appetite); return <section className="wellness-section"><div className="section-heading trend-heading"><div><div className="eyebrow">Descriptive only</div><h2>Your Wellness Trends</h2></div><label className="period-select">Time period<select value={period} onChange={(event) => setPeriod(event.target.value as WellnessPeriod)}>{Object.entries(periodLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><div className="stats-grid wellness-stats"><div><strong>{filtered.length}</strong><span>Days tracked</span></div><div><strong>{filtered.length ? `${average(filtered.map((record) => record.energy))}/5` : '—'}</strong><span>Average energy</span></div><div><strong>{filtered.length ? `${average(filtered.map((record) => record.sleepHours))} hrs` : '—'}</strong><span>Average sleep</span></div><div><strong>{mostCommon(moods) ?? '—'}</strong><span>Most common mood</span></div><div><strong>{mostCommon(appetites) ?? '—'}</strong><span>Most common appetite</span></div><div><strong>{mostCommon(filtered.map((record) => record.sleepQuality)) ?? '—'}</strong><span>Common sleep quality</span></div></div><Card className="graph-card"><div className="card-top"><div><h3>Energy & Sleep Trends</h3><p>Only recorded days are shown.</p></div><div className="metric-toggle"><button className={metric === 'energy' ? 'active' : ''} type="button" onClick={() => setMetric('energy')}>Energy</button><button className={metric === 'sleep' ? 'active' : ''} type="button" onClick={() => setMetric('sleep')}>Sleep</button></div></div><TrendGraph records={filtered} metric={metric} /></Card></section> }

export default function Wellness() { const [history, setHistory] = useState<WellnessRecord[]>(() => getWellnessHistory()); const todayRecord = history.find((record) => record.date === today) ?? null; const [editing, setEditing] = useState<WellnessRecord | null>(null); const [savedMessage, setSavedMessage] = useState(''); function refresh() { setHistory(getWellnessHistory()) } function handleSaved() { refresh(); setEditing(null); setSavedMessage('Wellness saved locally.'); window.setTimeout(() => setSavedMessage(''), 2500) } function handleClear() { if (window.confirm('Clear all wellness history from this device?')) { clearWellnessHistory(); refresh(); setEditing(null) } } function handleDelete(record: WellnessRecord) { if (window.confirm(`Delete the wellness record for ${formatDate(record.date)}?`)) { deleteWellnessRecord(record.id); refresh(); if (editing?.id === record.id) setEditing(null) } } return <><PageHeader eyebrow="Daily check-in" title="Wellness Tracker" description="Take a moment to check in with yourself." icon={HeartPulse} />{savedMessage && <div className="success-message" role="status"><Check size={16} />{savedMessage}</div>}<div className="wellness-layout"><WellnessForm key={editing?.id ?? todayRecord?.id ?? 'today-empty'} existing={editing ?? todayRecord} onSaved={handleSaved} /><div className="wellness-side"><Card className="today-card"><div className="eyebrow">Today</div><h2>{todayRecord ? 'Check-in saved' : 'Your day, your way'}</h2><p>{todayRecord ? `${todayRecord.mood} mood · ${todayRecord.energy}/5 energy · ${todayRecord.sleepHours} hrs sleep` : 'A small check-in can give you a useful snapshot of your day.'}</p></Card><Button variant="secondary" onClick={handleClear}><Trash2 size={16} />Clear Wellness History</Button></div></div><WellnessHistory records={history} onEdit={setEditing} onDelete={handleDelete} /><Trends records={history} /></> }
